#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 7777" \
    cd /code /code/.venv/bin/gunicorn wsgi:app -b 0.0.0.0:7777 -w 1 --timeout 15
